name: Run Tests
on: push
jobs:
  test:
    name: Test dexm.lol/${{ matrix.module }} on Go ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.18"]
        module: [channel]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: "~${{ matrix.go }}"
          check-latest: true
      - name: Run Tests
        run: go test -vet=all -timeout=1s -v ./${{ matrix.module }}
